version: "3"

services:

  demo-db:
    image: postgres

    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "energy_db", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=energy_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5433:5432"
    container_name: demo-db

  demo-be:
    image: spring
    restart: always
    ports:
      - "8080:8080"
    environment:
      #- DB_IP=172.22.0.2
      - DB_IP=demo-db
      - RABBIT_IP=demo-rabbit
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_DBNAME=energy_db
    container_name: demo-be
    depends_on:
      demo-db:
        condition: service_healthy

#    tomcat-db-api:
#       build: .
#       image: backend
#       ports:
#          - "8081:8080"
#       environment:
#          - DB_IP=db
#          - DB_DBNAME=energy_db
         
#       links:
#          - demo-db

# volumes:
#     db_volume:



    
